volumes:
  media:
  static:
  sqlite_data:

services:

  backend:
    container_name: foodgram-back
    build: ./backend/
    env_file:
      - .env
    volumes:
      - static:/backend_static
      - media:/app/media
      - sqlite_data:/data
    expose:
      - "8080"

  frontend:
    container_name: foodgram-front
    build: ./frontend/
    volumes:
      - static:/app/build/

  nginx:
    container_name: foodgram_proxy
    build: ./nginx/
    ports:
      - "8080:80"
    volumes:
      - media:/media
      - static:/static
    depends_on:
      - backend
      - frontend