# Generated by Django 3.2.25 on 2025-01-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='users/default_avatar.png', upload_to='users/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Данный адрес уже используется.'}, max_length=254, unique=True, verbose_name='Адрес эл. почты'),
        ),
    ]
